FROM debian

ENV WORKDIR="/servarr-dashboard"
ENV SERVARR_APP_DIR="$WORKDIR/app"
ENV SERVARR_CONF_DIR="$WORKDIR/config"
ENV SERVARR_LOG_DIR="$WORKDIR/log"
ENV SERVARR_THEME="overseerr"
ENV TRANSMISSION_COMPLETED_DIR="/media/downloads/completed"
ENV TRANSMISSION_INCOMPLETED_DIR="/media/downloads/incompleted"
ENV RPC_PASSWORD="transmission"
ENV RPC_USERNAME='transmission'
ENV RPC_AUTH_REQUIRED="true"
ENV FLARESOLVERR_VERSION="v3.3.13"
ENV FLARESOLVERR_LOG_LEVEL="info"
ENV FLARESOLVERR_LOG_HTML="false"
ENV FLARESOLVERR_CAPTCHA_SOLVER="none"
ENV FLARESOLVERR_TZ="UTC"
ENV FLARESOLVERR_LANG="none"
ENV FLARESOLVERR_HEADLESS="true" 
ENV FLARESOLVERR_BROWSER_TIMEOUT="40000" 
ENV FLARESOLVERR_TEST_URL="https://www.google.com"
ENV FLARESOLVERR_PORT="8191"
ENV FLARESOLVERR_HOST="0.0.0.0"
ENV FLARESOLVERR_PROMETHEUS_ENABLED="false"
ENV FLARESOLVERR_PROMETHEUS_PORT="8192"

ARG DEBIAN_FRONTEND=noninteractive

COPY setup.sh /setup.sh
RUN chmod +x /setup.sh
RUN bash /setup.sh
VOLUME "/media/downloads"
VOLUME $WORKDIR  

EXPOSE 80/tcp
EXPOSE 51413/tcp

ENTRYPOINT [ "bash", "/start.sh"]