version: '4'

services:
  servarr-dashboard:
    container_name: servarr-dashboard
    image: ldfe/servarr-dashboard
    restart: unless-stopped
    environment:
      - SERVARR_THEME="overseerr" # set this to change theme in app *arrs look -> https://docs.theme-park.dev/themes/sonarr/
      - TRANSMISSION_AUTH="true" # enable or not auth methode in tranmission
      - TRANSMISSION_USER="transmission" # user tranmission
      - TRANSMISSION_PASS="transmission" # pass tranmission
    volumes:
      - /AppData/servarr-dashboard:/servarr-dashboard # optional
      - /mnt:/media/downloads # optional
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started
        restart: true
        required: true

  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    hostname: gluetun 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /AppData/gluetun:/gluetun
    networks: 
      - servarr 
    restart: unless-stopped
    environment:
      - TZ=UTC
      - UPDATER_PERIOD=24h
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_USER=${OPENVPN_USER}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
    ports:
     - 80:80 # Port Web UI servarr-dashboard
     - 51413:51413 # Port Gluetun
     - 33242:33242/tcp  # Transmission Torrent Port TCP
     - 33242:33242/udp  # Transmission Torrent Port UDP 