version: '4'

services:
  servarr-dashboard:
    container_name: servarr-dashboard
    image: ldfe/servarr-dashboard
    restart: always
    environment:
      - SERVARR_THEME="overseerr" # set this to change theme in app *arrs look -> https://docs.theme-park.dev/themes/sonarr/
      - TRANSMISSION_AUTH="true" # enable or not auth methode on in tranmission
      - TRANSMISSION_USER="transmission" # default user tranmission
      - TRANSMISSION_PASS="transmission" # default pass tranmission
    volumes:
      - /opt/servarr/config:/config
      - /opt/servarr/nginx:/etc/nginx
      - /opt/servarr/app:/srv
      - /opt/servarr/logs:/var/log 
      - /opt/servarr/downloads:/media/downloads
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started
        restart: true
        required: true
  
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun # optional
    restart: unless-stopped
    environment:
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_USER=${OPENVPN_USER}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${TZ}
      - UPDATER_PERIOD=24h
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
    ports:
      - 51413:51413 # Gluetun port
      - 80:80 # Servarr Dashboard Port
      - 33242:33242/tcp  # Transmission Torrent Port TCP
      - 33242:33242/udp  # Transmission Torrent Port UDP 